#!/usr/bin/env python3

import sys, os, re
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]

# Figure out which branch we're on
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
print("commit-msg: On branch (%s)" % branch)
if branch == "secure-staging":
  print("Uh Oh you are on the wrong branch, please switch branch")
  sys.exit(1)

# Check the commit message what ticket we are working on
branch_str = branch.decode('utf-8')
idx = branch_str.index("/")
ticket_number = branch_str[idx + 1:]

with open(commit_msg_filepath, 'r') as f:
  content = f.read()
  if not content.startswith(ticket_number):
    print("commit-msg: ERROR! The commit message must start with '%s'" % ticket_number)
    sys.exit(1)
